/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oopm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Vishal
 */
public class addtask extends javax.swing.JFrame {

    int count = 0;
    static Connection conn = null;
    static PreparedStatement stmt;
    //Input:
    int duration = 0;
    String code; //am/pm
    int min, hrs;
    String task;
    /**
     * Creates new form
     */
    public addtask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        txtField_Duration = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD TIME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 80, 90, 22);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD TASK");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 190, 89, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(110, 230, 332, 84);

        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(230, 340, 110, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MINS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 130, 32, 16);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOURS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(110, 130, 50, 16);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(200, 150, 80, 30);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(110, 150, 80, 30);

        jToggleButton1.setForeground(new java.awt.Color(0, 102, 102));
        jToggleButton1.setText("AM");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(290, 150, 50, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 20, 50, 40);

        txtField_Duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField_DurationActionPerformed(evt);
            }
        });
        jPanel2.add(txtField_Duration);
        txtField_Duration.setBounds(380, 190, 60, 26);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Duration");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(380, 170, 55, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            estConnection();
            hrs = Integer.parseInt(jTextField4.getText());
            min = Integer.parseInt(jTextField3.getText());
            task = jTextArea1.getText();
            String code = jToggleButton1.getText();
            duration = Integer.parseInt(txtField_Duration.getText());
            if (hrs > 12 || hrs < 0 || min > 60 || min < 0) {
                JOptionPane.showMessageDialog(null, "Invalid Time");
            } else {
                if (code.equals("PM")) {
                    hrs += 12;
                }
                count++;
                System.out.println("Connection to SQLite has been established.");
                stmt = conn.prepareStatement("INSERT INTO ROUTINE (Task, Hours, Minutes, Duration) VALUES" + "(?,?,?,?)");
                stmt.setString(1, task);
                stmt.setInt(2, hrs);
                stmt.setInt(3, min);
                stmt.setInt(4, duration);
                stmt.executeUpdate();

                super.dispose();
                JOptionPane.showMessageDialog(null, "Task Added.");
                secretary s1 = new secretary();
                s1.setVisible(true);

            }
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }

        // create a connection to the database
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    static void estConnection() {
        if (conn == null) {
            conn = sqldb.javaDb();
        }
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.getText().equals("AM")) {
            jToggleButton1.setText("PM");
        }// TODO add your handling code here:
        else {
            jToggleButton1.setText("AM");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        super.dispose();
        secretary s1 = new secretary();
        s1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtField_DurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField_DurationActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtField_DurationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addtask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addtask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addtask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addtask.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addtask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtField_Duration;
    // End of variables declaration//GEN-END:variables
}
